export type ExpressionConfig = {
  eyeOpenness: number;   // 0=closed, 1=normal, 1.3=wide
  eyebrowY: number;      // negative = raised
  eyebrowTilt: number;   // degrees tilt
  mouthSmile: number;    // -1..1, negative = frown
  mouthOpen: number;     // 0..1
  mouthWidth: number;    // 0.5..1.5
  pupilX: number;        // horizontal gaze offset
  pupilY: number;        // vertical gaze offset
  pupilSize: number;     // 0.8=constricted, 1=normal, 1.2=dilated
  headTilt: number;      // degrees rotation
  cheekBlush: number;    // 0=none, 0.4=visible
  upperLidDroop: number; // 0=normal, 0.3=heavy (for thinking)
};

export const expressions: Record<string, ExpressionConfig> = {
  neutral: {
    eyeOpenness: 1,
    eyebrowY: 0,
    eyebrowTilt: 0,
    mouthSmile: 0,
    mouthOpen: 0,
    mouthWidth: 1,
    pupilX: 0,
    pupilY: 0,
    pupilSize: 1,
    headTilt: 0,
    cheekBlush: 0,
    upperLidDroop: 0,
  },
  smile: {
    eyeOpenness: 0.85,
    eyebrowY: -1,
    eyebrowTilt: 0,
    mouthSmile: 0.8,
    mouthOpen: 0.1,
    mouthWidth: 1.2,
    pupilX: 0,
    pupilY: 0,
    pupilSize: 1,
    headTilt: 0,
    cheekBlush: 0.4,
    upperLidDroop: 0,
  },
  thinking: {
    eyeOpenness: 0.9,
    eyebrowY: -2,
    eyebrowTilt: 5,
    mouthSmile: 0,
    mouthOpen: 0,
    mouthWidth: 0.8,
    pupilX: 0.4,
    pupilY: -0.4,
    pupilSize: 0.9,
    headTilt: 4,
    cheekBlush: 0,
    upperLidDroop: 0.3,
  },
  surprised: {
    eyeOpenness: 1.3,
    eyebrowY: -6,
    eyebrowTilt: 0,
    mouthSmile: 0,
    mouthOpen: 0.5,
    mouthWidth: 0.9,
    pupilX: 0,
    pupilY: 0,
    pupilSize: 0.85,
    headTilt: 0,
    cheekBlush: 0,
    upperLidDroop: 0,
  },
  concerned: {
    eyeOpenness: 1,
    eyebrowY: 2,
    eyebrowTilt: -8,
    mouthSmile: -0.3,
    mouthOpen: 0,
    mouthWidth: 0.9,
    pupilX: 0,
    pupilY: 0,
    pupilSize: 1,
    headTilt: -3,
    cheekBlush: 0,
    upperLidDroop: 0.1,
  },
  encouraging: {
    eyeOpenness: 0.95,
    eyebrowY: -2,
    eyebrowTilt: 0,
    mouthSmile: 0.6,
    mouthOpen: 0.15,
    mouthWidth: 1.1,
    pupilX: 0,
    pupilY: 0,
    pupilSize: 1.05,
    headTilt: 3,
    cheekBlush: 0.2,
    upperLidDroop: 0,
  },
  listening: {
    eyeOpenness: 1.05,
    eyebrowY: -1,
    eyebrowTilt: 0,
    mouthSmile: 0.1,
    mouthOpen: 0,
    mouthWidth: 1,
    pupilX: 0,
    pupilY: 0,
    pupilSize: 1.05,
    headTilt: 2,
    cheekBlush: 0,
    upperLidDroop: 0,
  },
  impressed: {
    eyeOpenness: 1.15,
    eyebrowY: -4,
    eyebrowTilt: 0,
    mouthSmile: 0.7,
    mouthOpen: 0.2,
    mouthWidth: 1.2,
    pupilX: 0,
    pupilY: 0,
    pupilSize: 1.1,
    headTilt: 0,
    cheekBlush: 0.3,
    upperLidDroop: 0,
  },
  questioning: {
    eyeOpenness: 1.1,
    eyebrowY: -3,
    eyebrowTilt: 10,
    mouthSmile: 0,
    mouthOpen: 0,
    mouthWidth: 0.9,
    pupilX: 0.2,
    pupilY: -0.2,
    pupilSize: 1,
    headTilt: -5,
    cheekBlush: 0,
    upperLidDroop: 0,
  },
  nodding: {
    eyeOpenness: 1,
    eyebrowY: 0,
    eyebrowTilt: 0,
    mouthSmile: 0.3,
    mouthOpen: 0,
    mouthWidth: 1,
    pupilX: 0,
    pupilY: 0,
    pupilSize: 1,
    headTilt: 0,
    cheekBlush: 0,
    upperLidDroop: 0,
  },
};
